### ISSUE TITLE
mpp_device_init failed to find device for coding 7 type 0

### ISSUE THREAD

**Issue by amiraeva** [AndreVallestero/vidware#2]
Hey,

I ran your script on my pinebook pro running Manjaro, and can't seem to fix this issue when trying to use rkmpp. Lots of dead ends all over the internet - was wondering if you managed to figure it out? Hardware accelerated video is the last thing I need to be able to use this as my daily driver.

Thanks!

```
[user@hostname]$ mpv --hwdec=rkmpp --vo=gpu demo.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
mpi: mpp version: 16e7f330 author: Herman Chen [dec_vproc]: Fix vproc stuck issue on reset
mpp_rt: NOT found ion allocator
mpp_rt: found drm allocator
hal_h264d_api: Assertion vcodec_type & ((1 << VPU_CLIENT_RKVDEC) | (1 << VPU_CLIENT_VDPU1) | (1 << VPU_CLIENT_VDPU2)) failed at hal_h264d_init:104
hal_h264d_api: hal_h264d_init hard mode error, value=0
hal_h264d_api: Assertion 0 failed at hal_h264d_init:154
mpp_device: mpp_device_init failed to find device for coding 7 type 0
Segmentation fault (core dumped)
```

**Comment by AndreVallestero** [comment]
Mpp requires kernel and DTS patches for the VPU.

For main line linux support using open source drivers, v4l2 is used however the open source drovers for the rk3399 vpu (hantro drivers) is currently not ready.

I'm working on trying to get patches from Armbian devs to work on manjaro however it seems like it will take some time.

**Comment by amiraeva** [comment]
Bummer, I look forward to when that gets working. Might have to use the stock debian OS in the meantime.
